version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: golfclub-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: golfclubdb
    ports:
      - "3307:3306"          
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: golfclub-api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/golfclubdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  mysql-data: